### ISSUE TITLE
CI_VERSION is ignored as it is not parsed in step.sh

### ISSUE THREAD

**Issue by kjoneandrei** [nodes-ios/bitrise-step-nodes-custom-script#26]
# Check if we have ci-version set correctly
	if [ -z "${CI_VERSION}" ]; then
		# not set, fallback to default CI version
		CI_VERSION=$DEFAULT_CI_VERSION
	fi
will always fail and set the CI_VERSION to default as CI_VERSION is an enviroment variable set later.

As a consequence the wrong parse project settings version will be used

**Comment by chriscombs** [comment]
The parse_project_settings step always uses the default because thats the step that assigns the CI_VERSION env var. We need the step.sh script to parse the ci version out of the yml by itself instead of relying on the env var.

**Comment by nickskull** [comment]
Fixed by #31
